import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; // Ensure this is present if using Tailwind
import { CartProvider } from "./context/CartContext";
import NavBar from "./components/orders/NavBar";
import Footer from "./components/orders/Footer";
import { Pacifico } from "next/font/google";
import { Chewy } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-pacifico",
});

const chewy = Chewy({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-chewy",
});

export const metadata = {
  title: "Mo's Cookie Dough",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${chewy.variable} ${pacifico.variable} antialiased`}
      >
        <CartProvider>
          <NavBar />
          {children}
          <Analytics />
        </CartProvider>
        <Footer />
      </body>
    </html>
  );
}
