import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; // Ensure this is present if using Tailwind
import { CartProvider } from "./context/CartContext";
import NavBar from "./components/orders/NavBar";
import Footer from "./components/orders/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mo's Cookie Dough",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <NavBar />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
